-- MySQL Script generated by MySQL Workbench
-- mié 14 nov 2018 09:19:30 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `coordenadas` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`coordenadas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `nombre` VARCHAR(45) NOT NULL,
  `productividad` VARCHAR(45) NULL,
  `coordenadas_v` INT NOT NULL,
  PRIMARY KEY (`nombre`, `coordenadas_v`),
  INDEX `coordenadas_idx` (`coordenadas_v` ASC),
  CONSTRAINT `coordenadas`
    FOREIGN KEY (`coordenadas_v`)
    REFERENCES `mydb`.`Vivero` (`coordenadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` VARCHAR(9) NOT NULL,
  `sueldo` FLOAT NULL,
  `antiguedad` INT NULL,
  `fecha_ini` DATE NULL,
  `fecha_fin` DATE NULL,
  `ventas` INT NULL,
  `nombre_v` VARCHAR(45) NULL,
  `coordenadas_v` INT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `nombre_idx` (`nombre_v` ASC, `coordenadas_v` ASC),
  CONSTRAINT `nombre`
    FOREIGN KEY (`nombre_v` , `coordenadas_v`)
    REFERENCES `mydb`.`Zona` (`nombre` , `coordenadas_v`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` VARCHAR(9) NOT NULL,
  `total_mes` INT NULL,
  `bonificacion` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `cod_prod` INT NOT NULL,
  `stock` INT NULL,
  `precio` INT NULL,
  PRIMARY KEY (`cod_prod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_Prod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_Prod` (
  `DNI` VARCHAR(9) NOT NULL,
  `cod_prod` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`DNI`, `cod_prod`, `fecha`),
  INDEX `cod_prod_idx` (`cod_prod` ASC),
  CONSTRAINT `dni`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_prod`
    FOREIGN KEY (`cod_prod`)
    REFERENCES `mydb`.`Producto` (`cod_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto_Zona` (
  `cod_prod` INT NOT NULL,
  `nombre_v` VARCHAR(45) NOT NULL,
  `coordenadas_v` INT NOT NULL,
  PRIMARY KEY (`cod_prod`, `nombre_v`, `coordenadas_v`),
  INDEX `nombre_idx` (`nombre_v` ASC, `coordenadas_v` ASC),
  CONSTRAINT `cod_prod`
    FOREIGN KEY (`cod_prod`)
    REFERENCES `mydb`.`Producto` (`cod_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nombre`
    FOREIGN KEY (`nombre_v` , `coordenadas_v`)
    REFERENCES `mydb`.`Zona` (`nombre` , `coordenadas_v`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Vivero`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Vivero` (`coordenadas`, `localidad`) VALUES (302030, 'La Laguna');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Zona`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Zona` (`nombre`, `productividad`, `coordenadas_v`) VALUES ('Almacen', '45', 302030);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Empleado`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Empleado` (`DNI`, `sueldo`, `antiguedad`, `fecha_ini`, `fecha_fin`, `ventas`, `nombre_v`, `coordenadas_v`) VALUES ('540636629T', 1500.0, 5, '23/02/2016', '23/02/2017', 5, 'Almacen', 302030);
INSERT INTO `mydb`.`Empleado` (`DNI`, `sueldo`, `antiguedad`, `fecha_ini`, `fecha_fin`, `ventas`, `nombre_v`, `coordenadas_v`) VALUES ('54063666T', 1400.3, 2, '23/02/2016', '23/05/2017', 8, 'Almacen', 302030);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Cliente` (`DNI`, `total_mes`, `bonificacion`) VALUES ('54063661T', 30, 2);
INSERT INTO `mydb`.`Cliente` (`DNI`, `total_mes`, `bonificacion`) VALUES ('54063660T', 56, 23);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Producto`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Producto` (`cod_prod`, `stock`, `precio`) VALUES (555555, 20, 20.3);
INSERT INTO `mydb`.`Producto` (`cod_prod`, `stock`, `precio`) VALUES (555554, 89, 12.3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Cliente_Prod`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Cliente_Prod` (`DNI`, `cod_prod`, `fecha`, `cantidad`) VALUES ('54063660T', 555555, '23/02/2017', 36);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Producto_Zona`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Producto_Zona` (`cod_prod`, `nombre_v`, `coordenadas_v`) VALUES (555555, 'Almacen', 302030);
INSERT INTO `mydb`.`Producto_Zona` (`cod_prod`, `nombre_v`, `coordenadas_v`) VALUES (555554, 'Almacen', 302030);

COMMIT;

